In [1]:
pip install numpy

                                              0.0/15.0 MB ? eta -:--:--
                                              0.1/15.0 MB 1.7 MB/s eta 0:00:10
                                              0.1/15.0 MB 1.4 MB/s eta 0:00:11
                                              0.2/15.0 MB 1.9 MB/s eta 0:00:08
                                              0.3/15.0 MB 1.9 MB/s eta 0:00:08
     -                                        0.5/15.0 MB 2.0 MB/s eta 0:00:08
     -                                        0.6/15.0 MB 2.0 MB/s eta 0:00:08
     -                                        0.6/15.0 MB 2.0 MB/s eta 0:00:08
     -                                        0.7/15.0 MB 2.1 MB/s eta 0:00:07
     -                                        0.7/15.0 MB 2.1 MB/s eta 0:00:07
     -                                        0.7/15.0 MB 2.1 MB/s eta 0:00:07
     -                                        0.7/15.0 MB 2.1 MB/s eta 0:00:07
     --                                       1.0/15.0 MB 1

In [2]:
import numpy as np

In [4]:
list1 = [5,8,9,15,35,52,26,4,20]

In [10]:
list1.append(21)

In [11]:
array_1d = np.array(list1)

In [12]:
array_1d

array([ 5,  8,  9, 15, 35, 52, 26,  4, 20, 20, 21])

In [16]:
list1 = [4,  5,  8,  9, 15, 20, 21, 26, 35, 52]

In [17]:
array_1d = np.array(list1)

In [18]:
array_1d

array([ 4,  5,  8,  9, 15, 20, 21, 26, 35, 52])

In [19]:
# calculate the max()
array_1d.max()

52

In [20]:
# calculate the min()
array_1d.min()

4

In [21]:
# calculate the mean()
array_1d.mean()

19.5

In [22]:
# calculate the standard deviation
array_1d.std()

14.333527130472806

In [23]:
# create a 2-dimensional array

array_2d = np.array([list1,list1])

In [24]:
array_2d

array([[ 4,  5,  8,  9, 15, 20, 21, 26, 35, 52],
       [ 4,  5,  8,  9, 15, 20, 21, 26, 35, 52]])

In [25]:
array_2d.min()

4

In [26]:
array_2d.max()

52

In [27]:
array_2d.mean()

19.5

In [28]:
# check the number of dimensions
array_2d.ndim

2

In [29]:
array_1d.ndim

1

In [30]:
# add 5 dimensions
array_5d = np.array([1,2,5,6,8], ndmin=5)

In [31]:
array_5d

array([[[[[1, 2, 5, 6, 8]]]]])

In [32]:
# add 3 dimensions
array_3d = np.array([1,2,5,6,8], ndmin=3)

In [33]:
array_3d

array([[[1, 2, 5, 6, 8]]])

In [34]:
# slicing arrays
list1[0:3]

[4, 5, 8]

In [35]:
# slicing a 1d array is basically the same as slicing a list
array_1d[0]

4

In [36]:
# slicing a 2d array, we need to specify position based on dimension
array_2d

array([[ 4,  5,  8,  9, 15, 20, 21, 26, 35, 52],
       [ 4,  5,  8,  9, 15, 20, 21, 26, 35, 52]])

In [37]:
array_2d[0,-3]

26

In [38]:
# 3d array
array_3d = np.array([[list1,list1],[list1,list1]])

In [39]:
array_3d

array([[[ 4,  5,  8,  9, 15, 20, 21, 26, 35, 52],
        [ 4,  5,  8,  9, 15, 20, 21, 26, 35, 52]],

       [[ 4,  5,  8,  9, 15, 20, 21, 26, 35, 52],
        [ 4,  5,  8,  9, 15, 20, 21, 26, 35, 52]]])

In [40]:
array_3d[0,1,5]

20

In [41]:
# both using one set of square brackets with commas, and using square brackets for each slice are valid notations
array_5d[0][0][0][0][2]

5

In [42]:
# we can also slice ranges of values in each sub-array
array_2d[0,3:9]

array([ 9, 15, 20, 21, 26, 35])

In [43]:
# generate random integer
x = np.random.randint(100)
x

48

In [44]:
# generate random float
x = np.random.rand()
x

0.016472831846185088

In [45]:
# generate a random array
x = np.random.randint(100, size=(5))
x

array([58, 54,  5, 27, 93])

In [46]:
# generate a random array
x = np.random.randint(100, size=(3,5))
x

array([[46, 13, 97, 19, 98],
       [90, 35, 98, 21, 75],
       [48, 95, 43, 67, 58]])

In [47]:
# generate a dataset from a normal distribution
# use loc parameter to set the mean, scale to set the stdev, size to set the size of the array
x = np.random.normal(loc=1, scale=2, size=(2,3))
x

array([[ 1.79974566,  3.44284179,  3.02348042],
       [-0.71481757, -1.64690164,  2.57425717]])

In [48]:
# generate data samples from a uniform distribution
x = np.random.uniform(size=(2,3))
x

array([[0.07643353, 0.98245164, 0.24275229],
       [0.1134729 , 0.96123865, 0.21865667]])